"""Explicit runtime governance states, kept visible in every receipt."""
REQUESTED = "REQUESTED"
AUTHORIZED = "AUTHORIZED"
ADMISSIBLE = "ADMISSIBLE"
EXECUTING = "EXECUTING"
CONTINUATION_VERIFIED = "CONTINUATION VERIFIED"
COMPLETED = "COMPLETED"
CONTAINED = "CONTAINED"
DENIED = "DENIED"


def admitted_trace() -> list[str]:
    return [REQUESTED, AUTHORIZED, ADMISSIBLE, EXECUTING, CONTINUATION_VERIFIED, COMPLETED]
